// Code generated by xkit template placeholder. DO NOT EDIT.

package server

import "google.golang.org/grpc"

type GeneratedGRPCServices struct{}

func RegisterGeneratedGRPCServices(srv grpc.ServiceRegistrar, services GeneratedGRPCServices) {
}
