// Code generated by xkit template placeholder. DO NOT EDIT.

package server

import httptransport "github.com/chnxq/xkitpkg/transport/http"

type GeneratedHTTPServices struct{}

func RegisterGeneratedHTTPServices(srv *httptransport.Server, services GeneratedHTTPServices) {
}
