// Code generated by xkit template placeholder. DO NOT EDIT.

package bootstrap

import (
	"fmt"

	"github.com/chnxq/xkitpkg/app"
	"github.com/chnxq/xkitpkg/transport"

	"xkit-template-v01/internal/server"
)

type GeneratedData struct{}

func NewGeneratedData(appCtx *app.AppCtx) (*GeneratedData, func(), error) {
	_ = appCtx
	return &GeneratedData{}, func() {}, nil
}

type GeneratedServices struct{}

func NewGeneratedServices(appCtx *app.AppCtx, data *GeneratedData) *GeneratedServices {
	_, _ = appCtx, data
	return &GeneratedServices{}
}

func (services *GeneratedServices) HTTP() server.GeneratedHTTPServices {
	_ = services
	return server.GeneratedHTTPServices{}
}

func (services *GeneratedServices) GRPC() server.GeneratedGRPCServices {
	_ = services
	return server.GeneratedGRPCServices{}
}

type GeneratedComponents struct {
	Data     *GeneratedData
	Services *GeneratedServices
}

func NewGeneratedComponents(appCtx *app.AppCtx) (*GeneratedComponents, func(), error) {
	data, cleanup, err := NewGeneratedData(appCtx)
	if err != nil {
		return nil, cleanup, err
	}

	services := NewGeneratedServices(appCtx, data)
	return &GeneratedComponents{
		Data:     data,
		Services: services,
	}, cleanup, nil
}

func (components *GeneratedComponents) Servers(appCtx *app.AppCtx) ([]transport.Server, error) {
	httpServer, err := server.NewHTTPServer(appCtx, components.Services.HTTP())
	if err != nil {
		return nil, fmt.Errorf("new generated http server: %w", err)
	}
	grpcServer, err := server.NewGRPCServer(appCtx, components.Services.GRPC())
	if err != nil {
		return nil, fmt.Errorf("new generated grpc server: %w", err)
	}
	return []transport.Server{httpServer, grpcServer}, nil
}

func NewGeneratedServers(appCtx *app.AppCtx) ([]transport.Server, func(), error) {
	components, cleanup, err := NewGeneratedComponents(appCtx)
	if err != nil {
		return nil, cleanup, err
	}

	servers, err := components.Servers(appCtx)
	if err != nil {
		return nil, cleanup, err
	}
	return servers, cleanup, nil
}
