// Code generated by xkit template placeholder. DO NOT EDIT.

package bootstrap

import (
	"github.com/chnxq/xkitpkg/app"
	"github.com/chnxq/xkitpkg/transport"

	taskruntime "xkit-template-v01/internal/task/runtime"
	"xkit-template-v01/internal/server"
)

type GeneratedData struct {
	AppContext *app.AppCtx
}

func NewGeneratedData(appCtx *app.AppCtx) (*GeneratedData, func(), error) {
	data := &GeneratedData{AppContext: appCtx}
	data.afterInit()
	return data, func() {}, nil
}

type generatedTaskService struct{}

func (generatedTaskService) TaskScheduler() *taskruntime.Scheduler { return nil }
func (generatedTaskService) TaskLogger() taskruntime.Logger        { return nil }

type GeneratedServices struct {
	Task      generatedTaskService
	TaskGroup generatedTaskService
}

func NewGeneratedServices(appCtx *app.AppCtx, data *GeneratedData) *GeneratedServices {
	services := &GeneratedServices{}
	_, _ = appCtx, data
	services.afterInit(data)
	return services
}

func (services *GeneratedServices) HTTP() server.GeneratedHTTPServices {
	_ = services
	return server.GeneratedHTTPServices{}
}

func (services *GeneratedServices) GRPC() server.GeneratedGRPCServices {
	_ = services
	return server.GeneratedGRPCServices{}
}

type GeneratedComponents struct {
	Data     *GeneratedData
	Services *GeneratedServices
}

func NewGeneratedComponents(appCtx *app.AppCtx) (*GeneratedComponents, func(), error) {
	data, cleanup, err := NewGeneratedData(appCtx)
	if err != nil {
		return nil, cleanup, err
	}

	services := NewGeneratedServices(appCtx, data)
	return &GeneratedComponents{
		Data:     data,
		Services: services,
	}, cleanup, nil
}

func (components *GeneratedComponents) Servers(appCtx *app.AppCtx, modules []hostModuleRuntime) ([]transport.Server, error) {
	httpServer, err := server.NewHTTPServer(appCtx, components.Services.HTTP(), components.Data, hostModuleHTTPRegistrars(modules))
	if err != nil {
		return nil, err
	}
	grpcServer, err := server.NewGRPCServer(appCtx, components.Services.GRPC(), components.Data, hostModuleGRPCRegistrars(modules))
	if err != nil {
		return nil, err
	}
	return []transport.Server{httpServer, grpcServer}, nil
}

func NewGeneratedServers(appCtx *app.AppCtx) ([]transport.Server, func(), error) {
	components, cleanup, err := NewGeneratedComponents(appCtx)
	if err != nil {
		return nil, cleanup, err
	}

	servers, err := components.Servers(appCtx, nil)
	if err != nil {
		return nil, cleanup, err
	}
	return servers, cleanup, nil
}
