// Code generated by xkit template placeholder. DO NOT EDIT.

package bootstrap

import "github.com/chnxq/xkitpkg/app"

func (data *GeneratedData) GetAppCtx() *app.AppCtx {
	if data == nil {
		return nil
	}
	return data.AppContext
}
