package bootstrap

// Add GeneratedData/GeneratedServices bootstrap hooks here.
// This file mirrors the extension file generated by xkit.

func (data *GeneratedData) afterInit() {}

func (services *GeneratedServices) afterInit(data *GeneratedData) {
	_, _ = services, data
}
