oss:
  minio:
    endpoint: "localhost:9000"
    upload_host: "localhost:9000"
    download_host: "localhost:9000"
    access_key: "root"
    secret_key: "~Xyz4321Ab"
    token: ""
    use_ssl: false
